platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'TicTacToe' do
  pod 'RIBs', :path => '../../../'
  pod 'RxSwift', '~> 5.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 5.0.1'
end
